spring:
  application:
    name: BFBManagement
    
  datasource:
    url: jdbc:postgresql://188.166.77.14:5432/BFBArchitecture
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: MZS%9Z1bXPem$Q
    
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false
        
  springdoc:
    api-docs:
      path: /v3/api-docs
      enabled: true
    swagger-ui:
      path: /swagger-ui.html
      enabled: true
      try-it-out-enabled: true
      operations-sorter: alpha
      tags-sorter: alpha
      display-request-duration: true
      doc-expansion: none
    show-actuator: false

bfb:
  scheduling:
    mark-late-job:
      enabled: true
      cron: "0 0 2 * * ?"

logging:
  level:
    com.bfb: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springdoc: DEBUG
    org.springframework.web: DEBUG
    org.postgresql: DEBUG  # ⬅️ Ajouté pour voir les logs PostgreSQL
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"